language: ruby
dist: trusty
sudo: required
bundler_args: --without benchmarks tools
script:
  - bundle exec rspec spec $RSPEC_OPTS
after_success:
  - "[ -d coverage ] && bundle exec codeclimate-test-reporter"
rvm:
  - 2.4.5
  - 2.5.5
  - 2.6.3
  - jruby-9.2.7.0
  - truffleruby
env:
  global:
    - COVERAGE=true
    - JRUBY_OPTS='--dev -J-Xmx1024M'
    - RSPEC_OPTS='--exclude-pattern spec/dry/struct/pattern_matching_spec.rb'
matrix:
  include:
    - rvm: 2.7
      env: "RSPEC_OPTS=''"
  allow_failures:
    - rvm: truffleruby
notifications:
  email: false
