language: ruby
dist: trusty
sudo: required
bundler_args: --without benchmarks tools
script:
  - bundle exec rake spec
after_success:
  - '[ "$TRAVIS_RUBY_VERSION" = "2.3.1" ] && [ "$TRAVIS_BRANCH" = "master" ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - rbx-3
  - jruby-9.1.5.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
